name = "cf-workers-telegram-bot"
main = "packages/worker/dist/worker/src/worker.mjs"

workers_dev = true
compatibility_date = "2023-10-13"

build.command = "npm install && npm run build:worker"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "llama2-db"
database_id = "58c55e70-5de8-4297-9fba-7b3503e60dd1"
