name = "cf-workers-telegram-bot-v2"
main = "packages/worker/src/worker.ts"

workers_dev = true
compatibility_date = "2024-11-11"

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "llama2"
database_id = "e24eb37b-6b13-4e84-b1af-63de0dedcc6d"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"

[[workflows]]
name = "telegram-edit-message-workflow"
binding = "EDIT_MESSAGE_WORKFLOW"
class_name = "EditMessageWorkflow"